# Generated by Django 5.1.6 on 2025-06-23 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('tipo_transacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transacao', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'tipo_transacao',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('transacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('data_transacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('aluno_id', models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
                ('tipo_transacao', models.ForeignKey(db_column='tipo_transacao', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.tipotransacao')),
            ],
            options={
                'db_table': 'transacao',
            },
        ),
    ]
