# Generated by Django 5.1.6 on 2025-06-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_tipotransacao_transacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='TipoPagamento',
        ),
    ]
