# Generated by Django 5.1.6 on 2025-06-23 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_delete_pagamento_delete_tipopagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.ForeignKey(blank=True, db_column='tipo_transacao', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.tipotransacao'),
        ),
    ]
