# Generated by Django 5.1.6 on 2025-06-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0004_alter_transacao_data_transacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsaveleducativo',
            name='salario',
            field=models.IntegerField(default=760.0),
        ),
    ]
