# Generated by Django 5.1.6 on 2025-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0007_alter_cuidadoespecial_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='saldo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
