# Generated by Django 5.1.6 on 2025-06-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0008_aluno_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cuidados_especias',
            field=models.ManyToManyField(blank=True, db_table='aluno_cuidados_especiais', null=True, to='data_hub.cuidadoespecial'),
        ),
    ]
