# Generated by Django 5.1.6 on 2025-06-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0009_alter_aluno_cuidados_especias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cuidados_especias',
            field=models.ManyToManyField(blank=True, db_table='aluno_cuidados_especiais', to='data_hub.cuidadoespecial'),
        ),
    ]
