# Generated by Django 5.1.6 on 2025-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0010_alter_aluno_cuidados_especias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='sala_id',
        ),
        migrations.AddField(
            model_name='sala',
            name='alunos',
            field=models.ManyToManyField(blank=True, db_table='sala_aluno', to='data_hub.aluno'),
        ),
    ]
