# Generated by Django 5.1.6 on 2025-06-21 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0011_remove_aluno_sala_id_sala_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('aluno_id', models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
    ]
