# Generated by Django 5.1.6 on 2025-06-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0012_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPAgamento',
            fields=[
                ('tipo_pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pagamento', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'tipo_pagamento',
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.ForeignKey(blank=True, db_column='tipo_pagamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.tipopagamento'),
        ),
    ]
