# Generated by Django 5.1.6 on 2025-06-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0013_tipopagamento_pagamento_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.ForeignKey(db_column='tipo_pagamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.tipopagamento'),
        ),
    ]
